Action readucers
Kwamay/React-Books pull request #2
Opened 2023-10-10 18:55 UTC by Kwamay

In this model, I...........
-[ ] Configured a Redux store

-[ ] Defined state of books that adds and remove reducer books

-[ ] Incuded a reducer that checks the status of reducer category

2023-10-10 19:27 UTC, OyePriscilla requested changes
Hi @Kwamay 👍 👍 👍 👍, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/103386183/196423863-0f522555-1b03-455e-a452-b822cdcfc398.gif)

## Highlights
`@reduxjs/toolkit` & `react-redux` present in `package.json`. ✔️ 
Structure of the files follow the `ducks pattern` ✔️ 
Configured a Redux store ✔️ 

## Required Changes ♻️
- [ ] Please kindly remove these commented code, this will make your codebase to be clean and more professional. 👍 

<img width="651" alt="Untitled" src="https://github.com/Kwamay/React-Books/assets/103386183/ff83cb17-8e13-4e37-8d3e-411fb10b8f76">

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-10 19:27 UTC, OyePriscilla commented on src/redux/categories/categoriesSlice.js
> +export default categoryReducer;
- [ ] Please as stated in the requirement, kindly use Redux Toolkit to create a slice for managing the state of `categories` in your Redux store. This [tutorial might be of help](https://redux-toolkit.js.org/tutorials/quick-start#create-a-redux-state-slice). 

<img width="651" alt="Untitled" src="https://github.com/Kwamay/React-Books/assets/103386183/9f2decdf-dfc6-4df3-992d-ce9f3a31050a">

2023-10-10 19:27 UTC, OyePriscilla commented on src/redux/books/booksSlice.js
> +export const removeBook = (id) => ({
- [ ] Please as stated in the requirement, kindly use Redux Toolkit to create a slice for managing a list of books in your Redux store. This [tutorial might be of help](https://redux-toolkit.js.org/tutorials/quick-start#create-a-redux-state-slice). 

<img width="651" alt="Untitled" src="https://github.com/Kwamay/React-Books/assets/103386183/a41d0429-1b6b-46eb-aee1-23d23eccfd1c">

2023-10-10 20:16 UTC, bellom commented
Dear Senior, 

Seems like a GH glitch, this commit 94c3e31 came in after the first CR review.

<img width="1323" alt="image" src="https://github.com/Kwamay/React-Books/assets/31897434/65fb8d8c-7671-4bf9-b0f3-8d0f8eafe8f3">

2023-10-11 21:57 UTC, fobadara approved these changes
Hi @Kwamay, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![APPRVED](https://user-images.githubusercontent.com/62938735/260206857-3c93f52c-5b21-4f6f-8bc4-be158a13d3cd.gif)
## Highlights
✅ Descriptive README
✅ Descriptive PR summary
✅ Clean code


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-11 22:00 UTC, merged